//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lithium.core.lib.net45.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.Interfaces = new HashSet<Interface>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int InstanceNo { get; set; }
        public int OwnerId { get; set; }
        public int ModelId { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual Model Model { get; set; }
        public virtual ICollection<Interface> Interfaces { get; set; }
    }
}
