//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lithium.core.lib.net45.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interface
    {
        public int Id { get; set; }
        public int InterfaceTypeId { get; set; }
        public int NetConnectorTypeId { get; set; }
        public int DeviceId { get; set; }
    
        public virtual InterfaceType InterfaceType { get; set; }
        public virtual NetConnectorType NetConnectorType { get; set; }
        public virtual Device Device { get; set; }
    }
}
