//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lithium.core.lib.net45.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfaceType
    {
        public InterfaceType()
        {
            this.Interfaces = new HashSet<Interface>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Interface> Interfaces { get; set; }
    }
}
