//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lithium.cli.net45
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetConnectorType
    {
        public NetConnectorType()
        {
            this.Interfaces = new HashSet<Interface>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Interface> Interfaces { get; set; }
    }
}
